import type { Metadata } from "next";
import React, { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Menu | Milestones-Grill | Open Table",
  description: "Generated by create next app",
};

const MenuLayout = ({ children }: { children: ReactNode }) => {
  return <>{children}</>;
};

export default MenuLayout;
