import type { Metadata } from "next";
import React, { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Reserve | Milestones Grill | Open Table",
  description: "Generated by create next app",
};

const ReserveLayout = ({ children }: { children: ReactNode }) => {
  return <>{children}</>;
};

export default ReserveLayout;
